[tox]
requires =
    tox >= 4.4
    pip >= 25.2  # required for python 3.15

envlist =
    coverage-erase
    py312
    py315
    coverage
    mypy
    ruff
    typos
    pep8

[testenv]
package = wheel
# Use the same wheel for all enviroments:
wheel_build_env = build_wheel
skip_install = true

[testenv:coverage-erase]
deps =
    coverage

commands =
    coverage erase

[testenv:py{3,312,313,314,315}]
# Use the generated blue-backup wheel for pytest:
skip_install = false

deps =
    pytest
    pytest-asyncio
    coverage

depends =
    coverage-erase

commands =
    coverage run -m pytest test.py {posargs}

[testenv:coverage]
deps =
    coverage

commands =
    coverage html
    coverage report --show-missing --fail-under=100

depends =
    py312
    py315

[coverage:run]
parallel = True
concurrency = multiprocessing
branch = True

[coverage:report]
exclude_also =
    raise NotImplementedError

[testenv:mypy]
deps =
    mypy ~= 2.3.1
    pytest

commands =
    mypy {posargs}

[testenv:ruff]
deps =
    ruff ~= 0.16.4

commands =
    ruff check {posargs}

[testenv:typos]
deps =
    typos ~= 1.49.0

commands =
    typos asyncrunner.py test.py {posargs}

[testenv:pep8]
deps =
    pycodestyle

commands =
    pycodestyle asyncrunner.py test.py {posargs}

[pycodestyle]
# Line length of 88 copied from black.
max-line-length = 88
